version: 2
jobs:
  build:
    docker:
      - image: circleci/python:jessie-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ls -lh
            python3 -m pytest -m smoke
      - store_artifacts:
          path: test-reports
          destination: test-reports
          when: always